config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/signup' => 'users#new', as: 'new_user'

  post '/signup' => 'users#create', as: 'users'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook'

  resources :users, except: [:new, :create] do
    resources :artworks
  end

  get '/users/:id/update_photo' => 'users#change_avatar', as: 'edit_avatar'

  post '/users/:id/update_photo' => 'users#update_avatar'

  get '/users/:id/upload_resume' => 'users#new_resume', as: 'new_user_resume'

  post '/users/:id/upload_resume' => 'users#attach_resume'

  patch '/users/:id/upload_resume' => 'users#attach_resume'

  get '/events/upcoming' => 'events#index'

  get '/events/past' => 'events#past_events', as: 'past_events'

  get '/events/:id/toggle_interest' => 'events#toggle_interest'

  resources :events do
    resources :comments, except: [:index, :show]
  end

  get '/events/:id/users' => 'events#users', as: 'event_users'

  get '/dashboard' => 'users#dashboard', as: 'dashboard'

  get '/current_user' => 'sessions#return_current_user'




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :login_required
  before_action :set_event
  before_action :set_comment, except: [:create]
  before_action :owner_required, only: [:edit, :update, :destroy]

  def create
    @comment = @event.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      render partial: "comments/comment_li", locals: { comment: @comment }, layout: false
    else
      render 'events/show'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @event
    else
      render "comments/edit"
    end
  end

  def destroy
    @comment.delete
    flash[:success] = "Comment has been deleted."

    redirect_to @event
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_event
    @event = Event.find_by(id: params[:event_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def owner_required
    return head(:forbidden) unless @comment.user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_li.html.erb
<li class="media mt-5">
  <% if comment.user.avatar.attached? %>
    <%= link_to image_tag(comment.user.avatar.variant(resize: "64x64"), class: "mr-3 rounded-lg"), user_path(comment.user) %>
  <% else %>
    <%= link_to image_tag("/assets/profile64.png", class: "mr-3 rounded-lg"), user_path(comment.user) %>
  <% end %>

  <div class="media-body">
    <span class="comment-head"><%= link_to comment.user.name, user_path(comment.user) %> </span>
    <small><%= comment.created_at.strftime("%d %b %Y %l:%M %p") %></small><br>
    <%= comment.body %> <br>
    <% if comment.user == current_user %>
      <%= link_to "Edit", edit_event_comment_path(@event, comment) %> <%= link_to "Delete", event_comment_path(@event, comment), method: :delete %>
    <% end %>
  </div>
</li>

app/views/comments/_form.html.erb
<%= display_errors(@comment) %>

<%= bootstrap_form_for([@event, @comment]) do |f| %>
  <%= f.text_area :body, :skip_label => true %>
  <%= f.submit "Create Comment", id: "create-comment" %>
<% end %>

app/views/comments/edit.html.erb
<div class="fill white-bg p-5">

  <h1>Edit Comment</h1>

  <%= render "form", {:event => @event, :comment => @comment} %>

</div>