config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/signup' => 'users#new', as: 'new_user'

  post '/signup' => 'users#create', as: 'users'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook'

  resources :users, except: [:new, :create] do
    resources :artworks
  end

  get '/users/:id/update_photo' => 'users#change_avatar', as: 'edit_avatar'

  post '/users/:id/update_photo' => 'users#update_avatar'

  get '/users/:id/upload_resume' => 'users#new_resume', as: 'new_user_resume'

  post '/users/:id/upload_resume' => 'users#attach_resume'

  patch '/users/:id/upload_resume' => 'users#attach_resume'

  get '/events/upcoming' => 'events#index'

  get '/events/past' => 'events#past_events', as: 'past_events'

  get '/events/:id/toggle_interest' => 'events#toggle_interest'

  resources :events do
    resources :comments, except: [:index, :show]
  end

  get '/events/:id/users' => 'events#users', as: 'event_users'

  get '/dashboard' => 'users#dashboard', as: 'dashboard'

  get '/current_user' => 'sessions#return_current_user'




end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  has_one_attached :resume
  has_many :artworks
  has_many :events
  has_many :comments
  has_many :interests
  has_many :events, through: :interests

  validates :email, uniqueness: :true,
                    presence: :true
  validates :password, presence: :true, on: :create

  def grab_image(image_url)
    downloaded_image = open(process_uri(image_url))
    self.avatar.attach(io: downloaded_image  , filename: "profile.jpg")
  end

  def past_events
    self.events.past_events
  end

  def upcoming_events
    self.events.future_events
  end 

  private

  def process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, :allow_redirections => :safe) do |r|
      r.base_uri.to_s
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except: [:new, :create]
  before_action :set_user, except: [:new, :create, :dashboard]
  before_action :owner_required, except: [:new, :show, :create, :dashboard]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      render 'users/welcome'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if update_user
      flash[:success] = "Your profile has been updated."
      redirect_to @user
    else
      render 'users/edit'
    end
  end

  def change_avatar
  end

  def update_avatar
    @user.avatar.purge

    update_user
    redirect_to @user
  end

  def new_resume
  end

  def attach_resume
    @user.resume.purge

    update_user
    redirect_to @user
  end

  def dashboard
    @events = current_user.upcoming_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :bio, :website, :avatar, :resume)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def update_user
    @user.update(user_params)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<%= display_errors(@user) %>

<%= bootstrap_form_for @user do |f| %>

  <%= f.file_field :avatar unless @user.avatar.attached? %>

  <%= f.email_field :email %>

  <%= f.text_field :name %>

  <%= f.text_area :bio %>

  <%= f.text_field :website %>

  <%= f.submit "Save" %>
<% end %>

app/views/users/change_avatar.html.erb
<div class="fill white-bg p-5">
  <h1>Update Profile Picture</h1>

  <p>Choose a new profile picture:</p>
  <%= form_tag edit_avatar_path(@user), method: :post, multipart: true do %>
    <%= file_field_tag 'user[avatar]', :class => "form-control" %>
    <%= submit_tag "Update" %>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="fill bg-white p-5">


  <h1>Welcome, <%= current_user.name %></h1>

  <h3>You have <%= pluralize(current_user.upcoming_events.count, "upcoming event") %>. </h3>

  <% if current_user.upcoming_events.any? %>
    <%= render :partial => 'events/table', locals: { :events => @events } %>
  <% else %>
    <p>You have haven't expressed interest in any upcoming events. Why not <%= link_to "browse upcoming events", events_path, class: "js-events-index-link" %>?</p>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="fill white-bg p-5">
  <h1>Edit Profile</h1>

  <%= render 'profile', :user => @user %>
</div>

app/views/users/new.html.erb
<div class="fill vc home-form">
  <div class="w-75 home-logo">
    <h1>Sign Up</h1>
    <%= display_errors(@user) %>

    <%= bootstrap_form_for @user do |f| %>

      <%= f.email_field :email %>

      <%= f.password_field :password %>

      <%= f.password_field :password_confirmation %>

      <%= f.submit "Sign Up" %>

    <% end %>
  </div>
</div>

app/views/users/new_resume.html.erb
<div class="fill white-bg p-5">

  <h1>Upload a Resume/CV</h1>

  <%= bootstrap_form_for @user, url: new_user_resume_path(@user) do |f| %>
    <%= f.label "Select the Resume/CV PDF you'd like to upload" %>
    <%= f.file_field :resume %>
    <br>
    <%= f.submit "Upload" %>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="fill bg-white p-5">

  <h1><%= @user.name %></h1>

  <p><%= link_to "Edit profile", edit_user_path(@user) if current_user == @user %></p>

  <%= image_tag(@user.avatar.variant(resize: "200x200")) if @user.avatar.attached?%>
  <br>
  <%= link_to "Change profile picture", edit_avatar_path if current_user == @user %>

  <p><%= "Website:" unless @user.website == "" || @user.website.nil? %> <%= link_to(@user.website) unless @user.website.nil? || @user.website == "" %></p>
  <p>Resume/CV: <br>
    <% if @user.resume.attached? %>
      <%= image_tag @user.resume.preview(resize: "200x200") %> <br>
      <%= link_to "View Resume/CV", url_for(@user.resume) %><br>
      <%= link_to "Update Resume/CV", new_user_resume_path(@user) %>
    <% elsif @user == current_user %>
      <%= link_to "Upload Resume/CV", new_user_resume_path(@user) %>
    <% else %>
      User has not uploaded a resume/CV.
    <% end %>
  </p>

  <h3>User Bio:</h3>
  <p><%= simple_format(@user.bio) %></p>

  <h3>Upcoming events:</h3>
  <% if @user.upcoming_events.any? %>
    <ul>
      <% @user.upcoming_events.each do |event| %>
        <li><%= link_to event.name, event_path(event) %> - <%= event.start_time.strftime("%A, %d %b %Y %l:%M %p") %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No upcoming events to show.</p>
  <% end %>

  <h3>Works:</h3>

  <% if @user.artworks.any? %>
  <%= link_to "Add Work", new_user_artwork_path(@user) %>

    <ul>
      <% @user.artworks.each do |artwork| %>
      <li>
        <a href="<%= user_artwork_path(@user, artwork) %>">
          <div class="artwork">
            <%= image_tag(artwork.images.first.variant(resize: "200x200")) %><br>
            <%= artwork.title %>, <%= artwork.date.strftime("%B %Y") %>
          </div>
        </a>
      </li>
      <% end %>
    </ul>
  <% elsif current_user == @user %>
    <p>You have not added any works to your profile.  You can begin by <%= link_to "adding one now", new_user_artwork_path(@user) %>.</p>
  <% else %>
    <p>This user has not added any works to their portfolio.</p>
  <% end %>

</div>

app/views/users/welcome.html.erb
<div class="fill bg-white p-5">
  <h1>Welcome to ArtHub!</h1>
  <h3>Please take a moment to complete your profile.</h3>

  <br><br>

  <%= render 'profile', :user => @user %>
</div>