config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/signup' => 'users#new', as: 'new_user'

  post '/signup' => 'users#create', as: 'users'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook'

  resources :users, except: [:new, :create] do
    resources :artworks
  end

  get '/users/:id/update_photo' => 'users#change_avatar', as: 'edit_avatar'

  post '/users/:id/update_photo' => 'users#update_avatar'

  get '/users/:id/upload_resume' => 'users#new_resume', as: 'new_user_resume'

  post '/users/:id/upload_resume' => 'users#attach_resume'

  patch '/users/:id/upload_resume' => 'users#attach_resume'

  get '/events/upcoming' => 'events#index'

  get '/events/past' => 'events#past_events', as: 'past_events'

  get '/events/:id/toggle_interest' => 'events#toggle_interest'

  resources :events do
    resources :comments, except: [:index, :show]
  end

  get '/events/:id/users' => 'events#users', as: 'event_users'

  get '/dashboard' => 'users#dashboard', as: 'dashboard'

  get '/current_user' => 'sessions#return_current_user'




end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :interests
  has_many :comments
  has_many :users, through: :interests
  has_one :location, dependent: :destroy
  has_one :city, through: :location
  
  accepts_nested_attributes_for :location

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :venue, presence: true
  validates :description, presence: true

  def self.past_events
    self.where("end_time < ?", Time.now).order('end_time desc')
  end

  def self.future_events
    self.where("end_time > ?", Time.now).order('start_time asc')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_required
  before_action :find_event, except: [:index, :new, :create, :past_events]
  before_action :owner_required, only: [:edit, :destroy, :update]

  def index
    @events = Event.future_events
    respond_to do |f|
      f.json {render json: @events}
      f.html {render 'events/index'}
    end
  end

  def past_events
    @events = Event.past_events
    respond_to do |f|
      f.json {render json: @events}
      f.html {render "past_events"}
    end 
  end

  def new
    @event = Event.new
    @event.location = Location.new(event: @event)

    render "new", layout: false
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      render json: @event, status: 201
    else
      render 'events/new', layout: false, status: 400
    end
  end

  def show
    @comment = Comment.new
    respond_to do |f|
      f.html {render 'show'}
      f.json {render json: @event}
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'events/edit'
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  def add_interest
    flash[:success] = "#{@event.name} has been added to your events."
    @event.users << current_user
    redirect_to @event
  end

  def remove_interest
    flash[:success] = "#{@event.name} successfully removed from your events."
    @event.users.delete(current_user)
    redirect_to @event
  end

  def toggle_interest
    if @event.users.include?(current_user)
      @event.users.delete(current_user)
    else
      @event.users << current_user
    end
    render json: current_user.events
  end

  def users
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_time, :end_time, :venue, :accepting_applications, :image, location_attributes: [:city_id, :area])
  end

  def owner_required
    return head(:forbidden) unless @event.user == current_user
  end

  def find_event
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_form.html.erb
<%= display_errors(@event) %>

<%= bootstrap_form_for @event do |f| %>

  <%# ROW 1 --- Title  %>
  <div class="form-row">
    <div class="col-12">
      <%= f.label "Event Title" %>
      <%= f.text_field :name, skip_label: true %>
    </div>
  </div>

  <%# ROW 2 --- Location Start_Time End_Time %>
  <div class="form-row">

    <%# COL 1 --- Location  %>
    <div class="col-6">
      <div class="form-row">
        <div class="col-12">
          <%= f.label "Location" %>
        </div>
      </div>

      <div class="form-row">


          <div class="col-3">
            <%= f.label :venue %>
          </div>
          <div class="col-9">
            <%= f.text_field :venue, skip_label: true %>
          </div>



        <%= f.fields_for :location do |location_form| %>

          <div class="form-group col-3">
            <%= f.label "Area", class: "col-form-label" %>
          </div>
          <div class="col-9">
            <%= location_form.text_field :area, skip_label: true %>
          </div>

          <div class="col-3">
            <%= f.label "City" %>
          </div>
          <div class="col-9">
            <%= location_form.select :city_id, City.all.collect { |c| [c.name, c.id] }, skip_label: true %>
          </div>
        <% end %>






      </div>
    </div>

    <div class="col-4">
      <div class="form-row">


          <%= f.datetime_field :start_time %>
        <!-- <div class="col-12">
          <%# f.label "Time" %>
          <%# f.datetime_field :start_time, ampm: true, skip_label: true %>
        </div> -->
      </div>


      <div class="form-row">
          <%= f.datetime_field :end_time %>
        <!-- <div class="col-6">
          <%# f.label "Time" %>
          <%# f.time_select :end_time, ampm: true, skip_label: true %>
        </div> -->
      </div>
    </div>
  </div>

  <%= f.text_area :description, size: '80X90' %>

  <%= f.check_box :accepting_applications %>

  <br>

  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/events/_table.html.erb
<table class="table">
  <tr>
    <th>Interested</th>
    <th>Image</th>
    <th>Event Title</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Venue</th>
    <th>Accepting Applications</th>
    <th>Users Interested:</th>
  </tr>

<% @events.each do |event| %>
    <tr>
      <td><%= event.users.include?(current_user) ?
        (image_tag "star32.png", class: "star", id: "star-#{event.id}", data: { id: "#{event.id}", state: 1}) :
         (image_tag "star-blank32.png", class: 'star', id: "star-#{event.id}", data: { id: "#{event.id}", state: 0}) %></td>
      <td><%= image_tag event.image.variant(resize: "150x150") if event.image.attached? %></td>
      <td><%= link_to event.name, event_path(event), data: {id: "#{event.id}"}, class: "js-event-link" %></td>
      <td><%= event.start_time.strftime("%m/%d/%Y %l:%M%p") %></td>
      <td><%= event.end_time.strftime("%m/%d/%Y %l:%M%p") %></td>
      <td><%= event.venue %></td>
      <td><%= event.accepting_applications ? "Yes" : "No" %></td>
      <td id="js-user-count-<%= event.id %>"><%= event.users.count %></td>
    </tr>

<% end %>

</table>

app/views/events/_user_li.html.erb
<li>
  <%= image_tag user.avatar.variant(resize: "100x100") %> <%= link_to(user.name, user_path(user)) %>
</li>

app/views/events/edit.html.erb
<div class="fill white-bg p-5">
  <h1>Edit Event</h1>

  <%= render "event_form", :event => @event %>
</div>

app/views/events/index.html.erb
<div class="fill bg-white p-5">

  <h1>Upcoming Events</h1>
  <div id="event_buttons">
    <%= button_tag 'New Event', type: 'button', class: "btn btn-outline-primary", id: "js-new-event" %>
    <%= button_tag "Past Events", type: 'button', class: "btn btn-outline-secondary", id: 'js-past-events' %>
  </div>
  <div  class="container">
    <div class="row">
      <div class=""></div>
      <div class="col-12">
        <div id="js-new-event-form"></div>
      </div>
      <div class=""></div>
    </div>
  </div>
  <%= render "table", :events => @events %>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col"></div>
<div class="col-7">
<div class="card event-form shadow">
  <div class="card-header">
    New Event
  </div>
  <div class="card-body">
    <%= render "event_form", :event => @event %>
  </div>
</div>
</div>
<div class="col"></div>
</div>

app/views/events/past_events.html.erb
<h1>Past Events</h1>

<%= link_to "Upcoming Events", events_path %>

<% if @events.any? %>
  <%= render "table", :events => @events %>
<% else %>
  <p>There are no past events.</p>
<% end %>

app/views/events/show.html.erb
<div class="fill white-bg p-5">
  <div class="row">
    <div class="col-12">
      <h1><%= @event.name %></h1>
      <p>Posted by: <%= link_to @event.user.name, user_path(@event.user)  %> at <%= @event.created_at.strftime("%d %b %Y %l:%M %p %Z") %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-5">
      <div id="event-buttons">
        <% if @event.user == current_user %>
          <%= link_to "Edit Event", edit_event_path(@event), class: "btn btn-primary btn-sm", role: "button" %>
          <%= link_to "Delete Event", event_path(@event), method: :delete, class: "btn btn-secondary btn-sm", role: "button" %>
        <% end %>

        <% if @event.users.include?(current_user) %>
          <%= image_tag "star32.png", class: "star", id: "star-#{@event.id}", data: {id: "#{@event.id}", state: "1"} %>
        <% else %>
          <%= image_tag "star-blank32.png", class: "star", id: "star-#{@event.id}", data: {id: "#{@event.id}", state: "0"}%>
        <% end %>
      </div>


      <br>
      <% if @event.image.attached? %>
        <%= link_to image_tag(@event.image.variant(resize: "400x400")), url_for(@event.image) %>
      <% end %>
    </div>

    <div class="col-xl">
      <h3 class="pt-4">Details</h3>
      <p>
        <strong>Start time: </strong> <%= @event.start_time.strftime("%A, %d %b %Y %l:%M %p %Z") %><br><br>
        <strong>End time: </strong> <%= @event.end_time.strftime("%A, %d %b %Y %l:%M %p %Z") %><br><br>
        <strong>Location: </strong> <%= @event.location.area %>, <%= @event.city.name %><br><br>
        <strong>Venue: </strong> <%= @event.venue %><br><br>
        <strong>Accepting Applications: </strong> <%= @event.accepting_applications ? "Yes" : "No" %><br><br>
        <strong>
          <% if @event.users.count == 0 %>
            There are 0 users interested in this event.
          <% else %>
            There <%= @event.users.count > 1 ? "are" : "is" %> <%= link_to pluralize(@event.users.count, "user"), event_users_path %> interested in this event.
          <% end %>
        </strong>
        <strong> </strong>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <h5>Event Description</h5>
      <p>
        <%= simple_format(@event.description) %>
      </p>
    </div>
  </div>


  <div class="row">
    <div class="col-12">
      <h3 class="border-top mt-1 pt-3">Comments</h3>
      <%= render "comments/form", {:event => @event, :comment => @comment} %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <ul id="js-new-comment" class="list-unstyled">
        <%= render :collection => @event.comments, :partial => "comments/comment_li", :locals => {:event => @event}, :as => :comment %>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/events/users.html.erb
<h1><%= pluralize(@event.users.count, "user") %> interested in <%= @event.name %></h1>

<%= link_to "Back to Event", event_path(@event) %>

<% if @event.users.any? %>
  <ul>
    <%= render :collection => @event.users, :partial => "user_li", :as => :user %>
  </ul>
<% else %>
  <p>There are no users to display.</p>
<% end %>