config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/signup' => 'users#new', as: 'new_user'

  post '/signup' => 'users#create', as: 'users'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook'

  resources :users, except: [:new, :create] do
    resources :artworks
  end

  get '/users/:id/update_photo' => 'users#change_avatar', as: 'edit_avatar'

  post '/users/:id/update_photo' => 'users#update_avatar'

  get '/users/:id/upload_resume' => 'users#new_resume', as: 'new_user_resume'

  post '/users/:id/upload_resume' => 'users#attach_resume'

  patch '/users/:id/upload_resume' => 'users#attach_resume'

  get '/events/upcoming' => 'events#index'

  get '/events/past' => 'events#past_events', as: 'past_events'

  get '/events/:id/toggle_interest' => 'events#toggle_interest'

  resources :events do
    resources :comments, except: [:index, :show]
  end

  get '/events/:id/users' => 'events#users', as: 'event_users'

  get '/dashboard' => 'users#dashboard', as: 'dashboard'

  get '/current_user' => 'sessions#return_current_user'




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArthubRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <a href="/" class="navbar-brand">
          <span class="nav-logo white-text">ArtHub</span></a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-links">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="nav-links">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Dashboard", dashboard_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Events", events_path, :class => "nav-link js-events-index-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Profile", user_path(current_user), :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", logout_path, method: :delete, :class => "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>

    <% if flash[:success] %>
      <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
      <% end %>

      <div class="container fill">

        <div id="js-container" class="fill">
          <%= yield %>
        </div>
      </div>

      <script id="table-row-template" type="text/x-handlebars-template">
        <tr>
          <td>{{{star}}}</td>
          <td><img src="{{imageUrl}}"/></td>
          <td>
            <a data-id="{{id}}" class="js-event-link" href="/events/{{id}}">{{name}}</a>
          </td>
          <td>{{startTime}}</td>
          <td>
          {{endTime}}
        </td>
        <td>{{venue}}</td>
        <td>{{acceptingApplications}}</td>
        <td id="js-user-count-{{id}}">{{userCount}}</td>
      </tr>
    </script>

    <script id="event-show-template" type="text/x-handlebars-template">
      <div class="fill white-bg p-5">

        <div class="row">
          <div class="col-12">
            <h1>{{name}}</h1>
            <p>Posted by:
              <a href="/users/{{owner.id}}">{{owner.name}}</a>
              at
              {{createdAt}}</p>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-5">
            <div id="event-buttons">
              {{{hbEventButtons}}}
            </div>

            <br>
            <a href="{{imageUrlFull}}"><img src="{{imageUrl400}}"/></a>
          </div>

          <div class="col-xl">
            <h3 class="pt-4">Details</h3>
            <p>
              <strong>Start time:
              </strong>
              {{startTime}}<br><br>
              <strong>End time:
              </strong>
            {{endTime}}<br><br>
            <strong>Location:
            </strong>
            {{area}},
            {{city}}<br><br>
            <strong>Venue:
            </strong>
            {{venue}}<br><br>
            <strong>Accepting Applications:
            </strong>
            {{acceptingApplications}}<br><br>
            <strong>
              There are
              {{userCount}}
              users interested in this event.
            </strong>
            <strong></strong>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <h5>Event Description</h5>
          <p>
            <p>{{{description}}}</p>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <h3 class="border-top mt-1 pt-3">Comments</h3>

          <form class="new_comment" id="new_comment" role="form" action="/events/{{id}}/comments" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;"/><%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <div class="form-group">
              <textarea class="form-control" name="comment[body]" id="comment_body"></textarea>
            </div>
            <input type="submit" name="commit" value="Create Comment" id="create-comment" class="btn btn-secondary" data-disable-with="Create Comment"/>
          </form>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          {{{hbListComments}}}
        </div>
      </div>
      
    </div>
  </script>

</body>
</html>